"""Initial tables

Revision ID: 27f4ac8e6a9e
Revises: 
Create Date: 2026-05-30 18:30:08.720230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27f4ac8e6a9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('suggested_action', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index('ix_anomalies_store_resolved_time', 'anomalies', ['store_id', 'resolved', 'triggered_at'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_dwell_ms', sa.Float(), nullable=True),
    sa.Column('queue_depth', sa.Float(), nullable=True),
    sa.Column('abandonment_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_metrics_snapshots_snapshot_time'), 'metrics_snapshots', ['snapshot_time'], unique=False)
    op.create_table('visitor_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('total_dwell_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_store_state_entry', 'visitor_sessions', ['store_id', 'current_state', 'entry_time'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_store_id'), 'visitor_sessions', ['store_id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_visitor_id'), 'visitor_sessions', ['visitor_id'], unique=False)
    op.create_table('zones',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('is_billing_zone', sa.Boolean(), nullable=True),
    sa.Column('polygon_coords', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_index(op.f('ix_zones_zone_id'), 'zones', ['zone_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('dwell_ms', sa.Integer(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_store_id'), 'events', ['store_id'], unique=False)
    op.create_index('ix_events_store_time', 'events', ['store_id', 'timestamp'], unique=False)
    op.create_index('ix_events_store_type_time', 'events', ['store_id', 'event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_visitor_id'), 'events', ['visitor_id'], unique=False)
    op.create_table('transactions',
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_time', sa.Time(), nullable=False),
    sa.Column('gmv', sa.Float(), nullable=False),
    sa.Column('nmv', sa.Float(), nullable=False),
    sa.Column('correlated_session_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_session_id'], ['visitor_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('invoice_number')
    )
    op.create_index(op.f('ix_transactions_correlated_session_id'), 'transactions', ['correlated_session_id'], unique=False)
    op.create_index(op.f('ix_transactions_invoice_number'), 'transactions', ['invoice_number'], unique=False)
    op.create_index('ix_transactions_store_time', 'transactions', ['store_id', 'order_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_store_time', table_name='transactions')
    op.drop_index(op.f('ix_transactions_invoice_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_correlated_session_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_events_visitor_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index('ix_events_store_type_time', table_name='events')
    op.drop_index('ix_events_store_time', table_name='events')
    op.drop_index(op.f('ix_events_store_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_zones_zone_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_visitor_sessions_visitor_id'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_store_id'), table_name='visitor_sessions')
    op.drop_index('ix_sessions_store_state_entry', table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    op.drop_index(op.f('ix_metrics_snapshots_snapshot_time'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_index('ix_anomalies_store_resolved_time', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
